<a href="https://colab.research.google.com/github/guddlaraji/files/blob/main/assessment__Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆)
(**hint**: import … as …)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)
(**hint**: np.\_\_version\_\_, np.show\_config)

In [3]:
np.__version__

'2.0.2'

#### 3. Create a null vector of size 10 (★☆☆)
(**hint**: np.zeros)

In [5]:
Z = np.zeros(10)

#### 4.  How to find the memory size of any array (★☆☆)
(**hint**: size, itemsize)

In [6]:
print(f"{Z.size * Z.itemsize} bytes")


80 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)
(**hint**: np.info)

In [ ]:
np.info(np.add)

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
(**hint**: array\[4\])

In [8]:
# Create a null vector of size 10
Z = np.zeros(10)

# Set the fifth value (index 4) to 1
Z[4] = 1

print(Z)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)
(**hint**: np.arange)

In [9]:
# Create a vector from 10 to 49
vector = np.arange(10, 50)
print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)
(**hint**: array\[::-1\])

In [10]:
# Create a sample vector
vector = np.arange(10, 20)  # Example: [10 11 12 ... 19]
# Reverse the vector
reversed_vector = vector[::-1]
print(reversed_vector)

[19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
(**hint**: reshape)

In [11]:
# Create values from 0 to 8
values = np.arange(9)
# Reshape into a 3x3 matrix
matrix = values.reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)
(**hint**: np.nonzero)

In [12]:
# Create the array
arr = np.array([1, 2, 0, 0, 4, 0])
# Find indices of non-zero elements
indices = np.nonzero(arr)
print(indices)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)
(**hint**: np.eye)

In [13]:
# Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)
(**hint**: np.random.random)

In [14]:
# Create a 3x3x3 array with random values
random_array = np.random.random((3, 3, 3))
print(random_array)

[[[0.65484666 0.26973476 0.42947197]
  [0.02395039 0.56191885 0.46835716]
  [0.22363136 0.72691951 0.46325105]]

 [[0.54730016 0.9762397  0.55042987]
  [0.56392712 0.97217272 0.8509343 ]
  [0.31343497 0.64371233 0.84201308]]

 [[0.85209201 0.7914601  0.29430644]
  [0.78537288 0.74543916 0.3870892 ]
  [0.88763864 0.32768464 0.36278461]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
(**hint**: min, max)

In [15]:
# Create a 10x10 array with random values
array = np.random.random((10, 10))
# Find the minimum and maximum values
min_val = array.min()
max_val = array.max()
print("Minimum value:", min_val)
print("Maximum value:", max_val)

Minimum value: 0.010928963397876523
Maximum value: 0.9996531937824921


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)
(**hint**: mean)

In [16]:
# Create a random vector of size 30
vector = np.random.random(30)
# Find the mean value
mean_val = vector.mean()
print("Mean value:", mean_val)

Mean value: 0.48520835032309456


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
(**hint**: array\[1:-1, 1:-1\])

In [18]:
# Create a 5x5 array of ones
array = np.ones((5, 5))
# Set the inside elements to 0
array[1:-1, 1:-1] = 0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
(**hint**: np.pad)

In [19]:
# Original array
array = np.array([[1, 2],
                  [3, 4]])
# Add a border of zeros (pad width = 1)
padded_array = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print(padded_array)

[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [20]:
print(0 * np.nan)        # Expression 1
print(np.nan == np.nan)  # Expression 2
print(np.inf > np.nan)   # Expression 3
print(np.nan - np.nan)   # Expression 4
print(0.3 == 3 * 0.1)    # Expression 5


nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
(**hint**: np.diag)

In [21]:
# Values to place below the main diagonal
values = [1, 2, 3, 4]
# Create a 5x5 matrix with these values below the diagonal (k=-1)
matrix = np.diag(values, k=-1)
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
(**hint**: array\[::2\])

In [22]:
# Create an 8x8 matrix of zeros
checkerboard = np.zeros((8, 8), dtype=int)
# Fill 1s in a checkerboard pattern
checkerboard[::2, 1::2] = 1  # Even rows, odd columns
checkerboard[1::2, ::2] = 1  # Odd rows, even columns
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
(**hint**: np.unravel_index)

In [23]:
# Shape of the array
shape = (6, 7, 8)
# Find the index of the 100th element (0-based indexing)
index = np.unravel_index(100, shape)
print(index)


(np.int64(1), np.int64(5), np.int64(4))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
(**hint**: np.tile)

In [25]:
# Tile the pattern to create an 8x8 matrix
checkerboard = np.tile(pattern, (4, 4))
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)
(**hint**: (x - min) / (max - min))

In [28]:
# Create a 5x5 random matrix
matrix = np.random.random((5, 5))
# Normalize the matrix
normalized_matrix = (matrix - matrix.min()) / (matrix.max() - matrix.min())
print("Original Matrix:\n", matrix)
print("\nNormalized Matrix:\n", normalized_matrix)

Original Matrix:
 [[0.10495642 0.64733751 0.59040762 0.89381278 0.09811301]
 [0.22959267 0.16152845 0.42063798 0.2079876  0.23533388]
 [0.59451593 0.45913185 0.39239433 0.42498925 0.86444896]
 [0.08524472 0.74831987 0.05014373 0.51490686 0.36672945]
 [0.84792207 0.01907735 0.92028763 0.85631255 0.07917515]]

Normalized Matrix:
 [[0.09529304 0.69712938 0.63395889 0.97062301 0.08769947]
 [0.23359178 0.15806644 0.44557928 0.2096184  0.23996234]
 [0.63851755 0.48829281 0.4142396  0.45040754 0.93804035]
 [0.07342056 0.80918131 0.03447184 0.55018182 0.38576136]
 [0.91970181 0.         1.         0.92901204 0.06668566]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
(**hint**: np.dtype)

In [29]:
# Define a custom dtype for RGBA
color_dtype = np.dtype([('r', np.uint8),
                        ('g', np.uint8),
                        ('b', np.uint8),
                        ('a', np.uint8)])

# Example: create an array of colors
colors = np.array([(255, 0, 0, 255), (0, 255, 0, 255)], dtype=color_dtype)

print(colors)
print(colors['r'])  # Access red channel


[(255,   0, 0, 255) (  0, 255, 0, 255)]
[255   0]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
(**hint**: np.dot | @)

In [30]:
# Create a 5x3 matrix
A = np.random.random((5, 3))
# Create a 3x2 matrix
B = np.random.random((3, 2))
# Matrix multiplication using np.dot
C_dot = np.dot(A, B)
# Matrix multiplication using @ operator
C_at = A @ B
print("Result using np.dot:\n", C_dot)
print("\nResult using @ operator:\n", C_at)


Result using np.dot:
 [[0.56797905 0.8130675 ]
 [0.49529901 0.56010994]
 [0.24955852 0.17683392]
 [0.50013238 0.79134666]
 [0.93375016 1.06026244]]

Result using @ operator:
 [[0.56797905 0.8130675 ]
 [0.49529901 0.56010994]
 [0.24955852 0.17683392]
 [0.50013238 0.79134666]
 [0.93375016 1.06026244]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
(**hint**: >, <=)

In [32]:
arr[(arr > 3) & (arr < 8)] *= -1
print(arr)

[ 1  2  0  0 -4  0]


#### 26. What is the output of the following script? (★☆☆)
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [42]:
# Using Python's built-in sum
print(sum(range(5), -1))
# Import everything from numpy
from numpy import *
# Using NumPy's sum
print(sum(range(5), -1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [43]:
Z = np.array([1, 2, 3, 4, 5])

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [47]:
# Create a float array with random values
arr = np.random.uniform(-10, 10, 10)  # 10 random floats between -10 and 10

# Round away from zero
rounded = np.copysign(np.ceil(np.abs(arr)), arr)

print("Original array:\n", arr)
print("Rounded away from zero:\n", rounded)


Original array:
 [-8.35270379 -6.9996486   7.92028541  7.47540295 -4.02424063 -4.71309164
  3.59422246  2.89245095 -3.81771485  2.22223741]
Rounded away from zero:
 [-9. -7.  8.  8. -5. -5.  4.  3. -4.  3.]


#### 30. How to find common values between two arrays? (★☆☆)
(**hint**: np.intersect1d)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)
(**hint**: np.seterr, np.errstate)

In [48]:
# Example arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7, 8])

# Find common values
common_values = np.intersect1d(a, b)

print("Common values:", common_values)


Common values: [4 5]


#### 32. Is the following expressions true? (★☆☆)
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
# Using regular sqrt
x1 = np.sqrt(-1)

# Using emath.sqrt (handles complex numbers)
x2 = np.emath.sqrt(-1)

print("np.sqrt(-1) =", x1)
print("np.emath.sqrt(-1) =", x2)

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
(**hint**: np.datetime64, np.timedelta64)

In [51]:
# Today
today = np.datetime64('today', 'D')

# Yesterday
yesterday = today - np.timedelta64(1, 'D')

# Tomorrow
tomorrow = today + np.timedelta64(1, 'D')

print("Yesterday:", yesterday)
print("Today    :", today)
print("Tomorrow :", tomorrow)


Yesterday: 2025-10-18
Today    : 2025-10-19
Tomorrow : 2025-10-20


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [52]:


# Start and end dates
start = np.datetime64('2016-07-01')
end = np.datetime64('2016-08-01')  # exclusive

# Generate all dates in July 2016
july_dates = np.arange(start, end, dtype='datetime64[D]')

print(july_dates)


['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [53]:
A = np.array([1, 2, 3, 4], dtype=float)
B = np.array([5, 6, 7, 8], dtype=float)
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(B, A, out=B)
print(B)

[ -3.  -8. -15. -24.]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [54]:
arr = np.random.uniform(0, 10, 5)
print("Original array:", arr)
int_part1 = np.floor(arr)
print("np.floor:", int_part1)
int_part2 = np.trunc(arr)
print("np.trunc:", int_part2)
int_part3 = arr.astype(int)
print("astype(int):", int_part3)
frac, int_part4 = np.modf(arr)
print("np.modf:", int_part4)
int_part5 = arr - arr % 1
print("Using %:", int_part5)


Original array: [6.74811036 3.22168523 3.25166928 8.24186082 8.79725683]
np.floor: [6. 3. 3. 8. 8.]
np.trunc: [6. 3. 3. 8. 8.]
astype(int): [6 3 3 8 8]
np.modf: [6. 3. 3. 8. 8.]
Using %: [6. 3. 3. 8. 8.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
(**hint**: np.arange)

In [55]:
# Method 1: Using np.tile
matrix1 = np.tile(np.arange(5), (5, 1))
print("Matrix using np.tile:\n", matrix1)

Matrix using np.tile:
 [[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
(**hint**: np.fromiter)

In [56]:
def my_gen():
    for i in range(10):
        yield i
arr = np.fromiter(my_gen(), dtype=int)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
(**hint**: np.linspace)

In [57]:
vector = np.linspace(0, 1, 12)[1:-1]
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)
(**hint**: sort)

In [58]:
arr = np.random.random(10)
print("Original array:\n", arr)
arr.sort()
print("\nSorted array:\n", arr)

Original array:
 [0.624115   0.30830448 0.64857799 0.67673701 0.12951987 0.08572534
 0.05010717 0.33401714 0.1670333  0.93977572]

Sorted array:
 [0.05010717 0.08572534 0.12951987 0.1670333  0.30830448 0.33401714
 0.624115   0.64857799 0.67673701 0.93977572]
