<a href="https://colab.research.google.com/github/guddlaraji/files/blob/main/Raji_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**30-07-2025**

**Introduction to Numpy**

In [ ]:
#what is Numpy?
#it is a core library for scientific computing in python
#The central object in Numpy is "Numpy Array's
#what is Numpy Array?
#High performence multidimensionalobjects which is designed specially for mathematical operations

In [ ]:
#How many types of array's?
#three types
#1D-Array:-An array with specific rows (axis =0) and No column
#2D-Array:-An array with both rows and columns is know 2D array
#3D-Array:- Multidimensional array's

In [ ]:
#what are all use cases and mathematical operations acheived by using Numpy?
"""
1.Dot product / Inner product
2.Matrix multiplication
3.solving the linear systems
4.inverse
5.determinent
6.element wise matrix multiplication
7.choose the random numbers
8.statistics   """

**installation of Numpy**

In [ ]:
! pip install numpy

In [ ]:
#import the library
import numpy as np

In [ ]:
#check the version of numpy
np.__version__

'2.0.2'

**The central object in numpy is Numpy Array'**

In [ ]:
#how can we create an array?
#array's can be created from existing data
a = np.array([1,2,3,4,5])
print(a)
#check the spae of above array "a"
a.shape
#find the dimension of the above array
a.ndim
#find the number of elements in above array
a.size
#find the size in bytes occupied by each element in above array "a"
a.itemsize
#find the data type of elements in above array
a.dtype

[1 2 3 4 5]


dtype('int64')

**Essential methods in Numpy**

In [ ]:
#access the element in the array
b = np.array([1,2,3])
#print the 2 from above array
print(b[1])
#reverse the entire array
print(b[::-1])

2
[3 2 1]


In [ ]:
#above array replace the "3" with "5"
b[2] = 5
print(b)

[1 2 5]


In [ ]:
#array--> ordered, immutable and allows the duplicates

**element wise maths operation**

In [ ]:
c = np.array([2,0,3])
print(b+c)
#Note:- when applying the arthematic operation on two array's. The array's has to be in same length or size
#what is vector addition?
#when we apply addition on array's of same length or size we call it as a vector addition

[3 2 8]


In [ ]:
d = np.array([5,6,7])
#find the sum of elements of above array
print(d.sum())
#find the minimum element from above array
print(d.min())
#i want to know maximum element from above array
print(d.max())

18
5
7


**Array's Vs List**

In [ ]:
l = [1,2,3]
#create an array from the above list
e = np.array(l)
#add the 4 in to above list
l.append(4)
print(l)

[1, 2, 3, 4]


In [ ]:
#add the new item to the array d
e.append(4)
print(e)
#we cannot add and remove the items from the array

In [ ]:
#How can we add the items into array?
#by creating the "New array"
a1 = e + np.array([6])
print(a1)
"""when we add a single element array to the existing array with different size, the new array
element is going to add with each element in the existing array this is known as
Broadcasting method"""

[7 8 9]


In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5])
arr3 = np.append(arr1,arr2)
print(arr3)

[1 2 3 4 5 1 2 3 4 5]


In [ ]:
#find the sqrt of each element in above arr1
print(np.sqrt(arr1))

[1.         1.41421356 1.73205081 2.         2.23606798]


**Dot Product**

In [ ]:
a = np.array([1,2])
b = np.array([3,4])
dot = 0
for i in range(len(a)):
  dot += a[i]*b[i]
print(dot)

11


In [ ]:
#define Dot product?
#vector multiplication of array's and sum of elements of result
#multiply each corresponding element and do the sum
#Note:- when we apply the dot product the array's must be in same size and same dimension

In [ ]:
#easy with numpy
dot = np.dot(a,b)
print(dot)

11


In [ ]:
#manual method
c = a*b
print(c)
d = np.sum(c)
print(d)

[3 8]
11


In [ ]:
e = a.dot(b)
print(e)

11


In [ ]:
f = a@b
print(f)

11


**31-07-2025**

In [ ]:
import numpy as np

In [ ]:
#create an array from
s1 = {1,2,3,4,5}
a = np.array(s1)
print(type(a))
print(a)

<class 'numpy.ndarray'>
{1, 2, 3, 4, 5}


In [ ]:
t1 = (1,2,3,4,5)
b = np.array(t1)
print(b)

[1 2 3 4 5]


**2D-Array**

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
#find the no of rows and columns
print(a.shape)
#find the dimensionality of an array
print(a.ndim)
#find the total elements in the array
print(a.size)
#find the element data types in the array
print(a.dtype)
print(a.itemsize)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int64
8


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
#How can we access the elements from array
#print the entire 1st row
#syntax:-   array[row_index,col_index]
print(a[0])
print(a[1])
print(a[1,1])
print(a[0,2])

[1 2 3]
[4 5 6]
5
3


In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#print the values of 1st column in above array
print(a[:,0])
#print the 3rd column values
print(a[:,2])

[1 5 9]
[ 3  7 11]


In [ ]:
#access only 10 11 12
print(a[2,1:4])
#print only 8 and 12
print(a[1:3,3])

[10 11 12]
[ 8 12]


In [ ]:
#print only 2 and 6
print(a[0:2,1])

[2 6]


In [ ]:
b = a[:,0]
for i in b:
  print(i)

1
5
9


**Transpose**

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


**matrix multiplication-->Dot product**

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[3,4],[5,6]])
# apply dot product on above arrays
c = np.dot(a,b)
print(c)
print(a@b)

[[13 16]
 [29 36]]
[[13 16]
 [29 36]]


**Inverse**

In [ ]:
a = np.array([[1,2],[3,4]])
d = np.linalg.inv(a)
print(d)

[[-2.   1. ]
 [ 1.5 -0.5]]


**Diagonal**

In [ ]:
e = np.diag(a)
print(e)

[1 4]


In [ ]:
#Note:- Diagonal on vectors return a matrix
c = np.diag([1,4,5])
print(c)

[[1 0 0]
 [0 4 0]
 [0 0 5]]


**Boolen Indexing**

In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
print(a>2)

[[False False]
 [ True  True]
 [ True  True]]


In [ ]:
#print the numbers
print(a[a>2])

[3 4 5 6]


In [ ]:
#check the numbers which is more then 2 and print True if more then 2 else print false
l = [1,2,3,4,5,6]
for i in l:
  if i >2:
    print(True)
  else:
    print(False)

False
False
True
True
True
True


In [ ]:
l = [1,2,3,4,5,6]
print(l*2)

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]


In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
print(a*2)

[[ 2  4]
 [ 6  8]
 [10 12]]


In [ ]:
#np.where(logic,True,False)
a = np.array([[1,2],[3,4],[5,6]])
#print the number greater then 2 and less then numbers print it as a -1
b = np.where(a>2,a,-1)
print(b)

[[-1 -1]
 [ 3  4]
 [ 5  6]]


In [ ]:
#2.compute the indexes where the condition is true
c = np.array([10,19,20,30,41,50,61])
#get the index position of even numbers
eve = np.argwhere(c%2==0).flatten()
print(eve)

[0 2 3 5]


In [ ]:
even2 = np.argwhere(a%2==0)
print(even2)

[[0 1]
 [1 1]
 [2 1]]


In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
even2 = np.argwhere(a%2==0)
a_even = a[even2[:,0],even2[:,1]]
print(a_even)

[2 4 6]


In [ ]:
#1. create 2d array--> np.array([[],[],[]])
#2. access the element from 2d array--> array[row_index,col_index]
#3. apply the dot product--> np.dot(arr1,arr2)
#4. transpose ---> Array.T
#5. diagonal of an array---> np.diag(array)
#6. inverse of an array ---> np.linalg.inv(array)
#7. boolen indexing ---> array > 2
#8. apply the condition in an array--> np.where(condition.True,False)
#9. compute the indexes in array where the comdition is true --> np.argwhere

**1-08-2025**

**Reshaping of Array**

In [ ]:
import numpy as np

In [ ]:
#create a range of array up to 10
a =np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#print a range of numbers from 1 to 10
b = np.arange(1,11)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#convert the array "b" in to 2 rows and 5 column
c = b.reshape(2,5)   #np.reshape(rows,cols)
print(c)
print(c.T)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [ ]:
#convert the array b into 5 rows and 2 column
d = b.reshape(5,2)
print(d)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [ ]:
#create a range of array from 1 to 6 and convert into 2 rows and 3 column
e = np.arange(1,7)
print(e)
f = e.reshape(2,3)
print(f)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
#what is the shape of e?
print(e.shape)

(6,)


np.newaxis-->it is used change the data in certain manner

In [ ]:
g = e[np.newaxis,:]
print(g)
print(g.shape)

[[1 2 3 4 5 6]]
(1, 6)


In [ ]:
h = e[:,np.newaxis]
print(h)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


**Concatenation**

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
#combine or concatenate above 2 array
c = np.concatenate((a,b), axis = 0)
print(c)
#Note:- when we give axis =0 cancatenate wrt row wise, axis=1 concatenate wrt columnwise
#when we give axis = None concatenate in 1D array format

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


**HSTACK**

In [ ]:
#hstack:- stack array aading in sequence  horizentally
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
h = np.hstack((a,b))
print(h)

[[1 2 5 6]
 [3 4 7 8]]


**VSTACK**

In [ ]:
#VSTACK :- STACK ARRAY ADDING IN SEQUENCE vertically
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
h = np.vstack((a,b))
print(h)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


**Broadcasting method-->** is apower mechanism tool that allows numpy to work with different arrays of different shape when performing the arthametic operations

In [ ]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
y = np.array([1,0,1])
z = x+y
print(z)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


**Copying of an array**

In [ ]:
a = np.array([1,2,3])
b = a
b[0] = 8
print(a)

[8 2 3]


In [ ]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 8
print(a)
print(b)
#np.copy is used when we make any changes in the new array it won't impac on the original arrays

[1 2 3]
[8 2 3]


**Generating Array's**

In [ ]:
#1.Genrate an array of zeros with  2 rows and 3 columns
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
a = np.zeros(3)
print(a)

[0. 0. 0.]


In [ ]:
#2.Generate an arrays of 1's with 2 rows and 3 columns
b = np.ones((2,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#3.generate an array specific number with particular rows and columns
c = np.full((3,3),5)
print(c)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [ ]:
#4.generate an identity matrix?
d = np.eye(4)
print(d)
#np.identity()

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#5.np.linspace(start,end,No. of Partititons):-splits the data in to n equal parts
e = np.linspace(0,10,5)
print(e)

[ 0.   2.5  5.   7.5 10. ]


**Generate random Numbers**

In [ ]:
#generate an array which is uniformaly distributed 0 to 1? with 3 rows and 2 column
a = np.random.random((3,2))
print(a)

[[0.66481977 0.91965305]
 [0.6562579  0.78595653]
 [0.55810407 0.20833957]]


In [ ]:
#generate an array which is normally distributed with 1000 rows
b = np.random.randn(1000)
#print(b)
#How can we say the data is normally distributed---> when the mean of that is equals to 0 and
#standard diviation is equal to 1 then the data is normally distributed
print(b.mean(),b.std())

0.060461269092475234 0.9712919832217078


In [ ]:
#generate an random integers?
c = np.random.randint(3,10, size=(3,2))
print(c)

[[3 5]
 [4 3]
 [3 7]]


In [ ]:
#generate an random numbers upto 6 in the size of 10 rows
d = np.random.choice(7,size=10)
print(d)

[2 0 4 0 3 4 6 4 2 3]


**Solving the linear systems**

In [ ]:
#x1 + x2 = 2200
#1.5x1 + 4x2 = 5050
#find the values of x1 and x2
a = np.array([[1,1],[1.5,4]])
b = np.array([2200,5050])
x = np.linalg.solve(a,b)
print(x)

[1500.  700.]


In [ ]:
"""
np.shape
np.ndim
np.size
np.dtype
np.itemsize
#what is 1d,2d,3d array's?
#what is the diff b/w list and array?
#How can we rehape an array ---> np.reshape(row,col)---> 2D data
#How can we apply the dot product---> np.dot(arr1,arr2)
#How can we generate an array specific number ---> np.full((ro,col),num)
#How can we copy an array---> np.copy()
#uniform distribution --> np.random.random((row,col))
#Normal distribution ---> np.random.randn(rows,col)
#randomintegers---> np.random.randint(start,end, size=(row,col))
#or--> np.random.choice(end,size=(row,col))"""